"""
Mock ticket data for DFW Operations Intelligence Copilot.

Contains 200 realistic DFW airport work order tickets distributed across
4 aging buckets for demonstration purposes.
"""

from datetime import datetime, timedelta
from typing import List, Dict, Any, Optional


def calculate_bucket(created_at: datetime) -> str:
    """Calculate aging bucket for a ticket based on creation date."""
    days_old = (datetime.now() - created_at).days

    if days_old <= 7:
        return "0-7 days"
    elif days_old <= 14:
        return "8-14 days"
    elif days_old <= 30:
        return "15-30 days"
    else:
        return "30+ days"


def generate_tickets() -> List[Dict[str, Any]]:
    """
    Generate 200 mock tickets with realistic DFW airport operations scenarios.
    Returns list of ticket dictionaries with computed datetime fields.
    """
    now = datetime.now()

    # Raw ticket data with days_ago for created_at calculation
    raw_tickets = [
        # ============================================================
        # BUCKET 1: 0-7 days (50 tickets) - Recent urgent operational issues
        # ============================================================
        {"id": 1, "title": "Terminal D HVAC system failure in Gate D18-D24 area", "status": "open", "priority": "critical", "days_ago": 1, "description": "HVAC system in Terminal D gates D18-D24 has failed. Temperature rising above 80F. Impacting passenger comfort and gate operations. Maintenance team dispatched. Estimated repair time 4-6 hours. May need temporary cooling units if not resolved quickly."},
        {"id": 2, "title": "Gate assignment conflict at Terminal A during morning peak", "status": "in_progress", "priority": "high", "days_ago": 2, "description": "Multiple flights assigned to Gate A15 between 6:00-8:00 AM. American Airlines AA2451 and Southwest WN1893 both scheduled. Gate operations coordinating with airlines for reassignment. Investigating root cause in gate management system."},
        {"id": 3, "title": "Baggage handling system delay at Terminal C", "status": "open", "priority": "high", "days_ago": 3, "description": "Baggage claim carousel 5 in Terminal C experiencing intermittent belt stoppage. Bags delayed 15-20 minutes. Passengers reporting missing luggage. Maintenance inspecting conveyor motor and sensors. May need belt replacement."},
        {"id": 4, "title": "Security checkpoint congestion at Terminal E - TSA PreCheck", "status": "open", "priority": "medium", "days_ago": 5, "description": "Terminal E TSA PreCheck lane experiencing 30+ minute wait times during peak hours (5:00-7:00 AM). Staffing levels appear adequate. Recommend reviewing lane configuration and passenger flow patterns per DFW Design Criteria Manual section 4.2."},
        {"id": 5, "title": "Aircraft de-icing equipment malfunction at Pad 3", "status": "open", "priority": "high", "days_ago": 6, "description": "De-icing truck #47 at Pad 3 experiencing hydraulic system failure. Fluid spray inconsistent. Winter weather approaching. Ground services coordinating backup equipment. Maintenance scheduled for tonight. Critical for winter operations readiness."},
        {"id": 6, "title": "Runway 17L FOD debris reported by pilot", "status": "in_progress", "priority": "critical", "days_ago": 0, "description": "United UA445 pilot reported potential FOD on Runway 17L near taxiway Bravo intersection. Airfield ops dispatched for inspection. Runway temporarily closed pending sweep. Air traffic control notified. Operations manual section 5.2 FOD procedures in effect."},
        {"id": 7, "title": "Terminal B power fluctuation affecting gate displays", "status": "open", "priority": "high", "days_ago": 1, "description": "Intermittent power fluctuations in Terminal B causing flight information displays to reset. Gates B12-B18 affected. Electrical team investigating UPS systems. May need to switch to backup power circuits."},
        {"id": 8, "title": "Skylink train emergency stop between Terminal A and B", "status": "resolved", "priority": "critical", "days_ago": 0, "description": "Skylink Train 2 experienced emergency stop due to door sensor malfunction. Passengers evacuated safely. Train removed from service. Technicians replacing faulty sensor assembly. Service restored with reduced frequency."},
        {"id": 9, "title": "Water main break near Terminal D curbside", "status": "in_progress", "priority": "high", "days_ago": 2, "description": "6-inch water main break at Terminal D arrivals level. Flooding affecting taxi staging area. Water shut off to section. Plumbing contractor on site. Traffic diverted to alternate pickup zone. Estimated repair 8-10 hours."},
        {"id": 10, "title": "Jetbridge hydraulic leak at Gate C22", "status": "open", "priority": "medium", "days_ago": 3, "description": "Jet bridge at Gate C22 showing hydraulic fluid seepage. Bridge functional but leak worsening. Gate remaining in service with monitoring. Maintenance scheduled for overnight repair window."},
        {"id": 11, "title": "Fire alarm false activation in Terminal A food court", "status": "resolved", "priority": "high", "days_ago": 1, "description": "Fire alarm activated in Terminal A food court near Gate A28. DFW Fire responded. Determined to be smoke detector triggered by cooking exhaust. System reset. Recommending HVAC adjustment for improved ventilation."},
        {"id": 12, "title": "Escalator #E-15 stopped at Terminal E connector", "status": "open", "priority": "medium", "days_ago": 4, "description": "Escalator E-15 at Terminal E international connector has stopped. Safety shutdown triggered by step misalignment. Technician scheduled for morning. Passengers using adjacent stairs and elevator."},
        {"id": 13, "title": "ATC communication interference on ground frequency", "status": "in_progress", "priority": "critical", "days_ago": 0, "description": "Ground control reporting intermittent radio interference on 121.65 MHz. Affecting aircraft taxi communications. FCC and FAA notified. RF sweep in progress to identify source. Backup frequency activated."},
        {"id": 14, "title": "Fuel farm pressure drop at Terminal E", "status": "in_progress", "priority": "high", "days_ago": 1, "description": "Fuel hydrant pressure dropped below minimum at Terminal E gates E31-E38. Aircraft refueling delayed. Investigating pump station and pipeline. Fuel trucks dispatched as backup. Coordinating with airlines on fuel requirements."},
        {"id": 15, "title": "Passenger medical emergency at Gate B15", "status": "resolved", "priority": "critical", "days_ago": 0, "description": "Passenger experienced cardiac event at Gate B15. DFW EMS responded within 3 minutes. AED deployed successfully. Patient transported to Parkland Hospital. Gate area cleared and returned to normal operations."},
        {"id": 16, "title": "Taxiway Alpha centerline light outage section 4", "status": "open", "priority": "high", "days_ago": 2, "description": "Taxiway Alpha centerline lights out in section 4 near Runway 18R intersection. NOTAM issued. Night operations require follow-me vehicle. Airfield electrical investigating transformer. Parts ordered."},
        {"id": 17, "title": "Terminal C roof leak above Gate C35", "status": "open", "priority": "medium", "days_ago": 5, "description": "Water intrusion reported at Gate C35 holdroom during recent rain. Ceiling tiles damaged. Temporary containment in place. Roofing contractor scheduled for inspection. Affects approximately 200 sq ft of ceiling area."},
        {"id": 18, "title": "Rental car shuttle bus breakdown on airport loop", "status": "resolved", "priority": "medium", "days_ago": 3, "description": "Hertz shuttle bus broke down on airport loop road near Terminal B. Blocking right lane temporarily. Bus removed by tow truck. Passengers transferred to backup vehicle. Traffic flow restored."},
        {"id": 19, "title": "Bird strike reported on Runway 13R", "status": "resolved", "priority": "high", "days_ago": 1, "description": "American AA1892 reported bird strike on departure from Runway 13R. Aircraft returned safely to gate. Wildlife management dispatched for runway inspection and dispersal. Species identification: large gull. Aircraft damage assessment in progress."},
        {"id": 20, "title": "Terminal A restroom flooding near Gate A22", "status": "in_progress", "priority": "medium", "days_ago": 2, "description": "Mens restroom near Gate A22 experiencing toilet overflow. Three fixtures affected. Area cordoned off. Plumbing team on site. Water extraction in progress. Directing passengers to alternate facilities."},
        {"id": 21, "title": "Automated parking garage gate malfunction Garage A", "status": "open", "priority": "medium", "days_ago": 4, "description": "Exit gate 3 at Garage A not reading parking tickets. Customers delayed. Manual override in use. Parking systems technician dispatched. May need reader replacement."},
        {"id": 22, "title": "Terminal D elevator #D-4 trapped passengers", "status": "resolved", "priority": "critical", "days_ago": 0, "description": "Elevator D-4 stopped between levels 1 and 2 with 6 passengers. Fire department responded. Passengers safely extracted within 15 minutes. Elevator locked out pending inspection by contractor."},
        {"id": 23, "title": "Catering truck collision with aircraft at Gate E12", "status": "in_progress", "priority": "critical", "days_ago": 1, "description": "LSG Sky Chefs catering truck struck Spirit NK472 aircraft at Gate E12. Minor damage to aircraft fuselage near door 2L. No injuries. Aircraft out of service pending inspection. Incident report filed. Investigation underway."},
        {"id": 24, "title": "WiFi outage affecting Terminal B concourse", "status": "open", "priority": "medium", "days_ago": 3, "description": "Public WiFi service down in Terminal B gates B20-B35. IT investigating access point failures. Multiple APs showing offline. May be related to earlier power fluctuation. Rebooting network equipment."},
        {"id": 25, "title": "Customs and Border Protection staffing shortage Terminal D", "status": "open", "priority": "high", "days_ago": 2, "description": "CBP reporting staffing shortage at Terminal D International Arrivals. Wait times exceeding 90 minutes for arriving international passengers. Working with CBP to increase officer deployment. Mobile passport lanes fully utilized."},
        {"id": 26, "title": "Ground power unit failure at Gate A8", "status": "open", "priority": "medium", "days_ago": 5, "description": "GPU at Gate A8 not providing stable power output. Voltage fluctuations affecting aircraft systems. Unit removed from service. Replacement GPU positioned. Maintenance reviewing unit for repair or replacement."},
        {"id": 27, "title": "Security door propped open at Terminal C sterile area", "status": "resolved", "priority": "high", "days_ago": 1, "description": "TSA reported security door at Terminal C near Gate C28 found propped open. Area secured within 5 minutes. No breach of sterile area confirmed. Door alarm was disabled. Investigating cause. Alarm system repaired."},
        {"id": 28, "title": "Potable water contamination concern Terminal E", "status": "in_progress", "priority": "high", "days_ago": 2, "description": "Passenger reported discolored water from fountain near Gate E22. Water samples collected for testing. Precautionary shutdown of affected water stations. Bottled water distributed. Awaiting lab results within 24 hours."},
        {"id": 29, "title": "Aircraft pushback tug fire at Gate B30", "status": "resolved", "priority": "critical", "days_ago": 0, "description": "Pushback tug experienced engine fire at Gate B30. Fire suppressed by operator with extinguisher. DFW Fire responded. No injuries. Aircraft evacuated as precaution. Tug towed to maintenance. Gate cleared for operations."},
        {"id": 30, "title": "Terminal A PA system audio distortion", "status": "open", "priority": "medium", "days_ago": 6, "description": "Public address system in Terminal A producing distorted audio. Announcements difficult to understand. Audio technician reviewing amplifier settings and speaker connections. May need component replacement."},
        {"id": 31, "title": "Airfield perimeter fence damage near cargo area", "status": "in_progress", "priority": "high", "days_ago": 1, "description": "Perimeter fence damaged near south cargo area. Approximately 10 feet of fencing down. Security posting guard. Fence contractor en route. TSA notified per security protocol. Wildlife risk increased."},
        {"id": 32, "title": "Jet fuel spill at hydrant station E-15", "status": "in_progress", "priority": "critical", "days_ago": 0, "description": "Approximately 50 gallons of Jet-A spilled at hydrant E-15 during aircraft refueling. Spill contained. Hazmat team on scene. Environmental contractor notified. Fuel operations suspended at gates E14-E16."},
        {"id": 33, "title": "Terminal D moving walkway stopped", "status": "open", "priority": "low", "days_ago": 4, "description": "Moving walkway between Gates D22 and D30 has stopped due to belt tracking issue. Passengers walking on stationary surface. Maintenance scheduled for overnight. Low priority due to alternate paths available."},
        {"id": 34, "title": "American Airlines lounge HVAC complaint", "status": "open", "priority": "low", "days_ago": 7, "description": "Admirals Club in Terminal C reporting temperature too warm. Thermostat showing 78F. HVAC technician adjusting air handling unit. May need to balance airflow with adjacent spaces."},
        {"id": 35, "title": "Runway 18R/36L closure for rubber removal", "status": "in_progress", "priority": "medium", "days_ago": 3, "description": "Scheduled rubber removal on Runway 18R/36L touchdown zone. NOTAM issued. Operations using alternate runway configuration. Work in progress by airport maintenance. Expected completion in 6 hours."},
        {"id": 36, "title": "Terminal B concession point of sale system down", "status": "open", "priority": "medium", "days_ago": 2, "description": "Multiple retail and food vendors in Terminal B reporting POS system failures. Unable to process credit cards. IT investigating network connectivity. Vendors accepting cash only temporarily."},
        {"id": 37, "title": "Emergency exit door alarm malfunction Terminal A", "status": "open", "priority": "high", "days_ago": 1, "description": "Emergency exit door near Gate A35 alarm not functioning. Door opens without triggering alert. Critical security concern. Door posted with security officer pending repair. Alarm contractor notified."},
        {"id": 38, "title": "Skylink platform screen door jammed at Terminal C", "status": "in_progress", "priority": "medium", "days_ago": 2, "description": "Platform screen door at Skylink Terminal C station stuck in partially open position. Safety risk. Station bypassed by trains. Passengers using alternate boarding points. Technician working on door mechanism."},
        {"id": 39, "title": "Deicing fluid tank level low at North deice pad", "status": "open", "priority": "high", "days_ago": 5, "description": "Type I deicing fluid storage tank at north deice pad at 15% capacity. Winter weather forecast for next week. Expedited delivery requested from supplier. Coordinating with airlines on deicing schedule adjustments."},
        {"id": 40, "title": "Terminal E international signage error", "status": "open", "priority": "low", "days_ago": 6, "description": "Wayfinding sign near Gate E31 showing incorrect direction to customs. Sign indicates left, should be right. Creating passenger confusion. Sign shop preparing corrected panel. Temporary directional signs posted."},
        {"id": 41, "title": "Cargo facility loading dock door stuck", "status": "in_progress", "priority": "medium", "days_ago": 3, "description": "Overhead door at cargo building dock 7 stuck in closed position. Motor failed. Freight operations impacted. Using alternate docks. Door company dispatched. Part may need to be ordered."},
        {"id": 42, "title": "Terminal C nursing room lock broken", "status": "open", "priority": "medium", "days_ago": 4, "description": "Nursing mothers room near Gate C15 has broken door lock. Room cannot be secured for privacy. Temporary out of service sign posted. Locksmith scheduled. Directing mothers to alternate location in Terminal B."},
        {"id": 43, "title": "Aircraft lavatory service truck leak", "status": "resolved", "priority": "medium", "days_ago": 2, "description": "Lavatory service truck #23 leaking waste at Gate A12 ramp area. Spill approximately 5 gallons. Area cordoned off. Cleaning crew dispatched. Truck removed from service. Environmental protocols followed."},
        {"id": 44, "title": "Terminal D automatic door sensor failure", "status": "open", "priority": "medium", "days_ago": 5, "description": "Automatic sliding doors at Terminal D curbside entrance not detecting pedestrians consistently. Doors staying closed. Manual operation required. Door technician evaluating sensor replacement needs."},
        {"id": 45, "title": "Airfield lighting vault flooding", "status": "in_progress", "priority": "high", "days_ago": 1, "description": "Airfield electrical vault near Runway 13L/31R has water intrusion. Sump pump failed. Risk to electrical equipment. Portable pump deployed. Electricians monitoring. Source of water ingress under investigation."},
        {"id": 46, "title": "Terminal A departure level traffic congestion", "status": "open", "priority": "medium", "days_ago": 3, "description": "Chronic traffic congestion at Terminal A departures during peak hours. Vehicle dwelling times excessive. Traffic officers deployed. Evaluating curb management improvements per Design Criteria Manual recommendations."},
        {"id": 47, "title": "Gate E8 jetbridge position indicator failure", "status": "open", "priority": "low", "days_ago": 7, "description": "Jetbridge at Gate E8 position indicator not displaying correctly in ops center. Bridge functions properly. Display issue only. Low priority as visual confirmation available. Technician scheduled."},
        {"id": 48, "title": "Terminal B CCTV camera offline Gates B25-B28", "status": "in_progress", "priority": "high", "days_ago": 2, "description": "Four CCTV cameras covering Gates B25-B28 showing offline status. Security coverage gap. IT investigating network switch. May be related to earlier WiFi issues. Security posting additional officers."},
        {"id": 49, "title": "Airfield vehicle speeding incident reported", "status": "open", "priority": "medium", "days_ago": 4, "description": "Report of ground service vehicle exceeding 25 mph speed limit on ramp near Terminal C. Vehicle identified as belonging to contractor. Incident documented. Safety briefing required for operator."},
        {"id": 50, "title": "Terminal D flight information display blank", "status": "in_progress", "priority": "medium", "days_ago": 1, "description": "Large flight information display at Terminal D ticketing showing blank screen. Power cycling attempted. Display hardware may have failed. Replacement unit being sourced from inventory."},

        # ============================================================
        # BUCKET 2: 8-14 days (50 tickets) - Ongoing operational maintenance
        # ============================================================
        {"id": 51, "title": "Runway 18R edge lighting system intermittent failures", "status": "in_progress", "priority": "high", "days_ago": 10, "description": "Runway 18R experiencing intermittent edge light failures in sections B and C. Airfield electricians investigating transformer issues. Temporary NOTAMs issued. Replacement parts ordered. Impacts night operations. Must resolve per FAA lighting standards and DFW Operations Manual section 7.3."},
        {"id": 52, "title": "Terminal B restroom facilities maintenance - Gate B30 area", "status": "open", "priority": "medium", "days_ago": 12, "description": "Multiple passenger reports of plumbing issues in Terminal B restrooms near Gate B30. Two toilets out of service, sink faucets dripping. Plumbing contractor scheduled for inspection. Need to ensure ADA compliance maintained. Temporary signage directing to alternate facilities."},
        {"id": 53, "title": "Automated People Mover train maintenance required", "status": "in_progress", "priority": "medium", "days_ago": 9, "description": "APM Train 3 showing increased brake wear indicators. Scheduled for overnight maintenance. Operating at reduced speed as precaution. Skylink system monitoring closely. Replacement parts available. Must maintain minimum service levels per DFW operational requirements."},
        {"id": 54, "title": "Gate bridge hydraulic system leak at Gate D15", "status": "open", "priority": "high", "days_ago": 8, "description": "Jet bridge at Gate D15 experiencing hydraulic fluid leak. Bridge operational but leak worsening. Staining concrete apron. Gate taken out of service for safety. Maintenance team isolating hydraulic lines. Environmental cleanup required."},
        {"id": 55, "title": "Airfield lighting inspection overdue - Taxiway Echo", "status": "open", "priority": "medium", "days_ago": 14, "description": "Taxiway Echo centerline and edge lights require quarterly inspection per FAA regulations. Last inspection 95 days ago. Scheduling nighttime airfield access. Coordinating with ATC for inspection windows. Must comply with FAA Part 139 requirements."},
        {"id": 56, "title": "Ground transportation staging area congestion Terminal C", "status": "open", "priority": "medium", "days_ago": 11, "description": "Taxi and ride-share staging area at Terminal C arrivals experiencing overflow during peak hours. Vehicles backing up onto service road. Traffic flow impacted. Ground transportation coordinator reviewing layout. May need temporary traffic management adjustments."},
        {"id": 57, "title": "Terminal A air conditioning unit repair", "status": "in_progress", "priority": "medium", "days_ago": 10, "description": "Rooftop AC unit #A-12 serving Gates A15-A20 showing reduced cooling capacity. Compressor showing signs of wear. Refrigerant levels checked - within spec. Fan motor bearing replacement scheduled. Parts on order."},
        {"id": 58, "title": "Cargo ramp lighting upgrade project", "status": "in_progress", "priority": "low", "days_ago": 13, "description": "Ongoing LED lighting upgrade at south cargo ramp. Phase 2 of 4 complete. New fixtures improving visibility and reducing energy consumption. Work progressing during overnight hours to minimize cargo operations impact."},
        {"id": 59, "title": "Terminal E wheelchair inventory shortage", "status": "open", "priority": "medium", "days_ago": 9, "description": "Terminal E international arrivals reporting wheelchair shortage during peak arrival banks. Current inventory: 15 chairs. Recommended minimum: 25. Procurement request submitted for 12 additional wheelchairs. Borrowing from other terminals temporarily."},
        {"id": 60, "title": "Parking Garage C elevator modernization", "status": "in_progress", "priority": "medium", "days_ago": 12, "description": "Elevator modernization project at Parking Garage C. Elevator 2 of 4 currently out of service for cab and controls upgrade. Work on schedule. Two elevators remaining operational. Expected completion in 5 days."},
        {"id": 61, "title": "Terminal D concession grease trap maintenance", "status": "open", "priority": "medium", "days_ago": 8, "description": "Food court grease traps in Terminal D requiring cleaning ahead of schedule due to higher than expected volume. Grease hauler scheduled for next available night. Some drains showing slow flow. Temporary measures in place."},
        {"id": 62, "title": "Airfield pavement markings faded - Taxiway Golf", "status": "open", "priority": "medium", "days_ago": 11, "description": "Taxiway Golf holding position markings at Runway 17R/35L intersection showing significant fading. Paint crew scheduled for restriping. Work requires runway closure coordination. Targeting next maintenance window in 4 days."},
        {"id": 63, "title": "Terminal B ceiling tile replacement program", "status": "in_progress", "priority": "low", "days_ago": 14, "description": "Systematic replacement of stained and damaged ceiling tiles in Terminal B concourse. Currently at Gate B22 area. Working during low-traffic overnight hours. Materials on site. Approximately 30% complete."},
        {"id": 64, "title": "Ground radar system calibration required", "status": "in_progress", "priority": "high", "days_ago": 9, "description": "Airport surface detection equipment (ASDE-X) showing drift in target positioning. FAA technicians scheduled for calibration. System remains operational with slightly reduced accuracy. Critical for low-visibility operations."},
        {"id": 65, "title": "Terminal C carpet replacement zones 3-4", "status": "in_progress", "priority": "low", "days_ago": 13, "description": "Carpet replacement project in Terminal C holdrooms zones 3-4 (Gates C20-C30). Contractor working in sections during overnight hours. Furniture moved and replaced each night. Quality of carpet meets DFW design standards."},
        {"id": 66, "title": "Employee parking lot pothole repairs", "status": "open", "priority": "low", "days_ago": 10, "description": "Multiple potholes reported in employee parking lot B near security checkpoint. Largest approximately 8 inches diameter. Temporary cold patch applied. Permanent asphalt repair scheduled for next dry weather window."},
        {"id": 67, "title": "Terminal A gate counter computer replacement", "status": "in_progress", "priority": "medium", "days_ago": 8, "description": "Systematic replacement of aging gate counter computers in Terminal A. Currently 12 of 20 complete. New systems provide faster check-in processing. Remaining gates scheduled over next week during overnight hours."},
        {"id": 68, "title": "Fire suppression system inspection - Parking Garage D", "status": "open", "priority": "high", "days_ago": 11, "description": "Annual fire suppression system inspection due for Parking Garage D. Fire marshal requiring completion within 30 days. Inspection contractor scheduled. Will require partial level closures during testing. Coordination with parking operations ongoing."},
        {"id": 69, "title": "Terminal E art installation maintenance", "status": "open", "priority": "low", "days_ago": 14, "description": "Public art installation near Terminal E security showing dust accumulation and one LED light panel out. Arts program coordinator arranging specialized cleaning and repair. Low priority but affects passenger experience."},
        {"id": 70, "title": "Runway 13R PAPI light alignment check", "status": "in_progress", "priority": "high", "days_ago": 9, "description": "Precision approach path indicator (PAPI) lights on Runway 13R due for flight check verification. FAA flight inspection scheduled. Preliminary ground checks complete. System appears within tolerance. Flight check will confirm."},
        {"id": 71, "title": "Terminal D window washing schedule delayed", "status": "open", "priority": "low", "days_ago": 12, "description": "Quarterly window washing for Terminal D landside delayed due to high winds last two weeks. Rebooking contractor for next available calm weather window. Windows showing visible soiling affecting natural light."},
        {"id": 72, "title": "Skylink station escalator overhaul Terminal A", "status": "in_progress", "priority": "medium", "days_ago": 10, "description": "Major overhaul of escalator at Terminal A Skylink station. Step chain and drive system replacement. One of two escalators out of service. Work progressing on schedule. Expected return to service in 3 days."},
        {"id": 73, "title": "Terminal B electrical panel upgrade", "status": "in_progress", "priority": "medium", "days_ago": 13, "description": "Electrical distribution panel upgrade in Terminal B mechanical room. Increasing capacity for planned concession expansion. Work requires coordinated power outages during overnight hours. Phase 2 of 3 complete."},
        {"id": 74, "title": "Airfield perimeter road resurfacing", "status": "open", "priority": "medium", "days_ago": 8, "description": "Perimeter road sections 12-15 showing significant cracking and deterioration. Safety concern for patrol vehicles. Engineering assessment complete. Resurfacing project scope being developed. Budget request in progress."},
        {"id": 75, "title": "Terminal C information kiosk repairs", "status": "open", "priority": "low", "days_ago": 11, "description": "Three of eight interactive information kiosks in Terminal C non-functional. Touch screens unresponsive. IT vendor scheduled for repairs. Replacement screens ordered. Remaining kiosks handling increased usage."},
        {"id": 76, "title": "Ground support equipment storage facility roof", "status": "open", "priority": "medium", "days_ago": 14, "description": "GSE storage building roof showing water stains on interior walls. Roof inspection identified failing membrane sections. Roofing contractor providing repair estimate. Temporary patches in place for next rain event."},
        {"id": 77, "title": "Terminal A flooring transition strips loose", "status": "open", "priority": "medium", "days_ago": 9, "description": "Multiple flooring transition strips between carpet and tile coming loose in Terminal A main corridor. Trip hazard concern. Temporary tape applied. Flooring contractor scheduled to resecure all affected strips."},
        {"id": 78, "title": "Baggage system motor replacement Terminal E", "status": "in_progress", "priority": "high", "days_ago": 10, "description": "Outbound baggage conveyor motor at Terminal E showing signs of failure. Vibration analysis indicates bearing wear. Replacement motor on site. Installation scheduled for overnight during lowest volume period."},
        {"id": 79, "title": "Terminal D family restroom renovation", "status": "in_progress", "priority": "low", "days_ago": 12, "description": "Family restroom renovation near Gate D20. Updating fixtures, flooring, and baby changing station. Work 60% complete. Temporary family restroom available at Gate D28. Expected completion in 4 days."},
        {"id": 80, "title": "Airfield drainage system cleaning", "status": "open", "priority": "medium", "days_ago": 8, "description": "Storm drainage system along Taxiway Delta showing reduced flow capacity. Debris accumulation suspected. Drainage contractor scheduled for vacuum cleaning. Heavy rain forecast next week increases urgency."},
        {"id": 81, "title": "Terminal E jet bridge software update", "status": "in_progress", "priority": "medium", "days_ago": 11, "description": "Software update deployment to jet bridge control systems at Terminal E. Update improves docking accuracy and adds diagnostic features. Gates E10-E20 complete. Remaining gates scheduled over next 3 nights."},
        {"id": 82, "title": "Parking revenue equipment calibration", "status": "open", "priority": "medium", "days_ago": 14, "description": "Quarterly calibration due for parking revenue equipment in all garages. Ensures accurate fee calculation and credit card processing. Vendor scheduled for systematic calibration over next week."},
        {"id": 83, "title": "Terminal B seating replacement program", "status": "in_progress", "priority": "low", "days_ago": 9, "description": "Replacement of worn holdroom seating in Terminal B gates B15-B25. Removing 15-year-old seats with new ergonomic design. Installation 40% complete. Positive passenger feedback on new seating."},
        {"id": 84, "title": "Fuel farm tank inspection", "status": "in_progress", "priority": "high", "days_ago": 10, "description": "API 653 inspection due for fuel storage tank #3. Tank drained and cleaned. Inspection in progress. Preliminary findings satisfactory. Full report expected in 5 days. Tank capacity temporarily reduced."},
        {"id": 85, "title": "Terminal C exterior lighting repair", "status": "open", "priority": "low", "days_ago": 13, "description": "Several exterior decorative lights at Terminal C entrance non-functional. Architectural lighting contractor scheduled. Replacement fixtures ordered. Does not affect safety lighting. Cosmetic concern only."},
        {"id": 86, "title": "Employee shuttle bus fleet maintenance", "status": "in_progress", "priority": "medium", "days_ago": 8, "description": "Scheduled preventive maintenance for employee shuttle bus fleet. Rotating buses through service. Four of twelve buses completed. Maintaining full service with remaining fleet. No service disruptions expected."},
        {"id": 87, "title": "Terminal A retail power circuit upgrade", "status": "open", "priority": "medium", "days_ago": 11, "description": "Power capacity upgrade needed for new retail tenant in Terminal A. Current circuit insufficient for planned equipment. Electrical engineering reviewing options. Work may require overnight outages in adjacent spaces."},
        {"id": 88, "title": "Airfield emergency phone system test", "status": "open", "priority": "high", "days_ago": 14, "description": "Quarterly testing of airfield emergency phone stations overdue. 47 stations require functional verification. Testing schedule coordinated with operations. Critical for airfield safety per FAA requirements."},
        {"id": 89, "title": "Terminal D wastewater pump maintenance", "status": "in_progress", "priority": "medium", "days_ago": 9, "description": "Duplex wastewater pump station serving Terminal D food court requiring pump rebuild. One pump remains operational. Rebuild of second pump in progress. Parts arrived. Expected completion in 2 days."},
        {"id": 90, "title": "Skylink track inspection report review", "status": "open", "priority": "medium", "days_ago": 12, "description": "Annual Skylink track inspection complete. Report identifies minor wear items requiring attention. Prioritizing repair schedule based on findings. No immediate safety concerns. Budget allocation for repairs in progress."},
        {"id": 91, "title": "Terminal E duty free storage expansion", "status": "open", "priority": "low", "days_ago": 10, "description": "Duty free concessionaire requesting additional storage space in Terminal E. Evaluating options in adjacent support areas. Requires coordination with customs bond requirements. Space planning in progress."},
        {"id": 92, "title": "Ground radar display upgrade ops center", "status": "in_progress", "priority": "medium", "days_ago": 13, "description": "Upgrading ASDE-X display monitors in airport operations center. New high-resolution displays improve situational awareness. Installation 75% complete. Training scheduled for operations staff."},
        {"id": 93, "title": "Terminal B tenant HVAC rebalancing", "status": "open", "priority": "low", "days_ago": 8, "description": "New restaurant tenant in Terminal B reporting temperature inconsistencies. HVAC test and balance contractor scheduled. Will require adjustment of air handling unit serving that zone."},
        {"id": 94, "title": "Perimeter intrusion detection system test", "status": "in_progress", "priority": "high", "days_ago": 11, "description": "Quarterly functional test of perimeter intrusion detection system in progress. Testing all fence-line sensors and camera integration. Two sensor zones showing degraded response. Repair technicians notified."},
        {"id": 95, "title": "Terminal C charging station installation", "status": "in_progress", "priority": "low", "days_ago": 14, "description": "Installation of additional device charging stations in Terminal C holdrooms. Adding USB and wireless charging to existing furniture. 8 of 15 stations complete. Passenger feedback positive."},
        {"id": 96, "title": "Airfield guidance sign reflectivity check", "status": "open", "priority": "medium", "days_ago": 9, "description": "Annual reflectivity testing for airfield guidance signs due per FAA requirements. Testing equipment scheduled. Preliminary visual inspection identified 12 signs potentially below standards."},
        {"id": 97, "title": "Terminal A tenant build-out inspection", "status": "open", "priority": "medium", "days_ago": 12, "description": "Final inspection required for new food vendor build-out in Terminal A near Gate A28. Contractor requesting certificate of occupancy. Fire, health, and building inspections scheduled for next week."},
        {"id": 98, "title": "Deicing pad lighting upgrade", "status": "in_progress", "priority": "medium", "days_ago": 10, "description": "LED lighting upgrade at north deicing pad. Improving visibility for winter operations. Phase 1 complete - pad lighting. Phase 2 - fluid containment area - in progress. Winter weather readiness priority."},
        {"id": 99, "title": "Terminal D passenger counter system", "status": "open", "priority": "low", "days_ago": 13, "description": "Passenger counting sensors at Terminal D security showing calibration drift. Counts lower than actual throughput. Vendor scheduled for recalibration. Data accuracy affects staffing forecasts."},
        {"id": 100, "title": "Employee badging office HVAC issue", "status": "open", "priority": "low", "days_ago": 8, "description": "Employee credentialing office reporting inadequate cooling. Staff uncomfortable during peak appointment hours. HVAC technician evaluated - supplemental cooling unit recommended. Procurement in progress."},

        # ============================================================
        # BUCKET 3: 15-30 days (50 tickets) - Medium-term planning and projects
        # ============================================================
        {"id": 101, "title": "Terminal E concourse expansion - preliminary planning", "status": "in_progress", "priority": "medium", "days_ago": 22, "description": "Terminal E passenger capacity approaching design limits during peak hours. Facilities planning team conducting feasibility study for additional gates and holdroom space. Reviewing DFW Design Criteria Manual specifications. Coordinating with airlines on gate allocation impacts. 30% planning complete."},
        {"id": 102, "title": "Airfield pavement maintenance - Taxiway Foxtrot rehabilitation", "status": "open", "priority": "medium", "days_ago": 28, "description": "Taxiway Foxtrot pavement condition index (PCI) rating dropped to 62 (fair condition). Surface cracking and joint deterioration observed. Planning asphalt rehabilitation project for next maintenance window. Estimating 45-day closure. Budget approval pending."},
        {"id": 103, "title": "Terminal D HVAC preventive maintenance schedule", "status": "in_progress", "priority": "high", "days_ago": 18, "description": "Quarterly HVAC preventive maintenance for Terminal D overdue by 3 weeks due to staffing constraints. Seven rooftop units require filter changes, coil cleaning, and refrigerant checks per HVAC Design Manual specifications. Scheduling contractor for overnight work."},
        {"id": 104, "title": "Baggage claim carousel upgrade proposal - Terminal A", "status": "open", "priority": "low", "days_ago": 25, "description": "Terminal A baggage claim carousels 1-4 are 18 years old and approaching end-of-life. Proposing upgrade to newer high-efficiency models with improved passenger information displays. Capital project proposal in review. Estimated cost $2.3M."},
        {"id": 105, "title": "Security checkpoint expansion planning - Terminal B", "status": "open", "priority": "medium", "days_ago": 20, "description": "Terminal B security checkpoint consistently exceeding 20-minute wait times during peak periods. TSA and DFW operations reviewing expansion options. Evaluating space for 2 additional screening lanes. Design Criteria Manual review required."},
        {"id": 106, "title": "Terminal A gate podium replacement program", "status": "in_progress", "priority": "low", "days_ago": 24, "description": "Gate podiums in Terminal A showing age and wear. Technology outdated. Replacement program approved for 20 podiums. Vendor selected. First units arriving next month. Installation sequence being planned to minimize disruption."},
        {"id": 107, "title": "Airfield wildlife management plan review", "status": "open", "priority": "medium", "days_ago": 16, "description": "Annual review of wildlife hazard management plan required per FAA Part 139. Current plan expires in 45 days. Wildlife biologist assessment complete. Updated plan in draft. FAA coordination scheduled."},
        {"id": 108, "title": "Terminal C restroom renovation project", "status": "in_progress", "priority": "medium", "days_ago": 21, "description": "Major renovation of Terminal C restroom facilities near Gates C10-C15. Expanding capacity and updating fixtures. Construction 35% complete. Temporary facilities in place. Targeting completion before summer peak."},
        {"id": 109, "title": "Ground service equipment tracking system", "status": "open", "priority": "medium", "days_ago": 27, "description": "Proposal to implement GPS tracking for airport-owned ground service equipment. Improves utilization and maintenance scheduling. RFP development in progress. Budget allocated for FY2026. Vendor demonstrations scheduled."},
        {"id": 110, "title": "Terminal D fire alarm system upgrade", "status": "open", "priority": "high", "days_ago": 17, "description": "Fire alarm system in Terminal D approaching end of support life. Manufacturer discontinuing parts in 18 months. Engineering assessment complete. Recommending full system replacement. Capital project request submitted."},
        {"id": 111, "title": "Employee parking expansion study", "status": "open", "priority": "low", "days_ago": 23, "description": "Employee parking lots at 95% capacity during peak shifts. Study underway for expansion options including new surface lot and potential garage. Land use evaluation in progress. Coordination with HR on shift scheduling alternatives."},
        {"id": 112, "title": "Terminal E retail concession rebid", "status": "in_progress", "priority": "medium", "days_ago": 19, "description": "Current retail concession agreement for Terminal E expiring in 8 months. RFP development in progress. Market research complete. Targeting diverse vendor mix with local presence. Proposal evaluation criteria being finalized."},
        {"id": 113, "title": "Airfield emergency response drill planning", "status": "open", "priority": "high", "days_ago": 26, "description": "Full-scale emergency response drill required per FAA Part 139.325. Previous drill was 32 months ago. Planning committee formed. Scenario development in progress. Targeting drill execution in 60 days. Multi-agency coordination underway."},
        {"id": 114, "title": "Terminal B information display upgrade", "status": "open", "priority": "medium", "days_ago": 15, "description": "Flight information display system in Terminal B using outdated technology. Replacement displays selected. Installation planning in progress. Phased approach to maintain continuous information availability. Budget approved."},
        {"id": 115, "title": "Skylink vehicle midlife overhaul planning", "status": "in_progress", "priority": "medium", "days_ago": 22, "description": "Skylink trains approaching 12-year midlife overhaul milestone. Scope includes propulsion system rebuild, interior refurbishment, and safety system updates. Contract negotiations with manufacturer in progress. First vehicle scheduled Q3."},
        {"id": 116, "title": "Terminal A curbside reconstruction design", "status": "open", "priority": "medium", "days_ago": 28, "description": "Terminal A curbside showing pavement deterioration and outdated traffic flow design. Engineering study recommending reconstruction with improved layout. Design phase funded. Consultant selection in progress. Construction targeted for next year."},
        {"id": 117, "title": "Fuel hydrant system expansion Terminal E", "status": "open", "priority": "medium", "days_ago": 18, "description": "Terminal E fuel hydrant system at capacity with new gate additions. Engineering study for system expansion complete. Recommending additional hydrant loops and increased pump capacity. Capital project in budget review."},
        {"id": 118, "title": "Terminal C elevator modernization project", "status": "in_progress", "priority": "medium", "days_ago": 24, "description": "Elevator modernization project at Terminal C. Four elevators total - two complete, two remaining. Scope includes new controls, motors, and cab interiors. Work progressing on schedule. ADA compliance verified."},
        {"id": 119, "title": "Airfield snow removal equipment procurement", "status": "open", "priority": "medium", "days_ago": 20, "description": "Fleet assessment identified need for two additional snow removal vehicles. Current fleet aging with maintenance costs increasing. Procurement specifications developed. RFQ issued. Delivery targeted before next winter season."},
        {"id": 120, "title": "Terminal D tenant improvement allowance program", "status": "open", "priority": "low", "days_ago": 29, "description": "Review of tenant improvement allowance program for Terminal D concessions. Current program structure may not support desired tenant mix. Evaluating incentive structures used at peer airports. Recommendations due in 30 days."},
        {"id": 121, "title": "Ground transportation waiting area expansion", "status": "open", "priority": "low", "days_ago": 16, "description": "Ground transportation waiting areas at Terminals C and D undersized for ride-share demand. Evaluating expansion options including covered waiting areas. Coordination with ride-share companies on signage and pickup zones."},
        {"id": 122, "title": "Terminal E apron reconstruction planning", "status": "in_progress", "priority": "medium", "days_ago": 23, "description": "Terminal E aircraft apron showing concrete deterioration in multiple panels. Pavement evaluation complete. Reconstruction project in design phase. Phased approach required to maintain gate operations. Construction in 2027."},
        {"id": 123, "title": "Airport operations center technology refresh", "status": "open", "priority": "medium", "days_ago": 19, "description": "Operations center technology platforms approaching end of life. Video wall, workstations, and integration systems need refresh. Technology assessment complete. Budget request for FY2026 submitted. Vendor demonstrations ongoing."},
        {"id": 124, "title": "Terminal B food court expansion study", "status": "open", "priority": "low", "days_ago": 27, "description": "Terminal B food court seating at capacity during peak periods. Study evaluating expansion options including adjacent holdroom space conversion. Passenger survey results positive for additional dining options. Feasibility analysis in progress."},
        {"id": 125, "title": "Perimeter road security lighting upgrade", "status": "open", "priority": "medium", "days_ago": 17, "description": "Perimeter road lighting assessment identified multiple dark spots. Security concern for patrol operations. LED upgrade project scoped. 47 fixtures identified for replacement or addition. Funding request in budget process."},
        {"id": 126, "title": "Terminal A baggage handling system optimization", "status": "in_progress", "priority": "medium", "days_ago": 25, "description": "Baggage handling system efficiency study for Terminal A. Current sortation rate below industry benchmark. Consulting with system manufacturer on optimization strategies. Testing modified operating parameters. Results promising."},
        {"id": 127, "title": "Aircraft rescue firefighting station renovation", "status": "open", "priority": "medium", "days_ago": 21, "description": "ARFF Station 2 facility assessment identified deferred maintenance items. Living quarters and apparatus bay improvements needed. Design phase authorized. Temporary accommodations planning underway for construction period."},
        {"id": 128, "title": "Terminal C public art installation project", "status": "open", "priority": "low", "days_ago": 30, "description": "Public art program planning new installation for Terminal C renovated areas. Artist selection complete. Fabrication in progress. Installation coordinated with terminal renovation timeline. Targeting unveiling during terminal reopening."},
        {"id": 129, "title": "Airfield drainage improvement project", "status": "in_progress", "priority": "medium", "days_ago": 16, "description": "Airfield drainage study identified areas of standing water during heavy rain. Engineering design for improvements complete. Construction contract awarded. Work to begin during dry season. Environmental permits obtained."},
        {"id": 130, "title": "Terminal D signage and wayfinding update", "status": "open", "priority": "low", "days_ago": 22, "description": "Terminal D wayfinding signage outdated after gate renumbering. Comprehensive signage update program in design. Coordinating with Design Criteria Manual standards. Installation phased to minimize passenger confusion."},
        {"id": 131, "title": "Employee shuttle fleet electrification study", "status": "open", "priority": "low", "days_ago": 28, "description": "Feasibility study for converting employee shuttle fleet to electric vehicles. Evaluating charging infrastructure requirements. TCO analysis comparing diesel to electric. Results favor electric with 7-year payback. Planning implementation timeline."},
        {"id": 132, "title": "Terminal E security camera system upgrade", "status": "in_progress", "priority": "high", "days_ago": 18, "description": "Security camera system upgrade at Terminal E. Replacing analog cameras with IP-based high-definition system. Installation 60% complete. Integration with central monitoring in progress. Improved coverage and image quality."},
        {"id": 133, "title": "Runway 17R/35L rubber removal contract", "status": "open", "priority": "medium", "days_ago": 24, "description": "Annual rubber removal contract for Runway 17R/35L due for rebid. Current contract expires in 60 days. Specifications updated to include environmental requirements. RFP being finalized for release next week."},
        {"id": 134, "title": "Terminal A VIP lounge development", "status": "open", "priority": "low", "days_ago": 20, "description": "Airline partner requesting new VIP lounge space in Terminal A. Site options being evaluated. Design criteria review with airline in progress. Lease terms under negotiation. Construction timeline dependent on agreement."},
        {"id": 135, "title": "Ground power unit fleet replacement", "status": "open", "priority": "medium", "days_ago": 29, "description": "Ground power unit fleet assessment complete. 8 of 24 units beyond economic repair threshold. Replacement procurement initiated. Evaluating electric GPU options for sustainability goals. Delivery timeline 6-8 months."},
        {"id": 136, "title": "Terminal B nursing room expansion", "status": "in_progress", "priority": "low", "days_ago": 15, "description": "Expansion of nursing mothers facilities in Terminal B per passenger feedback. Adding second nursing room near Gate B20. Construction underway. Furnishing selections made per Design Criteria Manual. Opening in 3 weeks."},
        {"id": 137, "title": "Airfield pavement marking contract renewal", "status": "open", "priority": "medium", "days_ago": 23, "description": "Airfield pavement marking contract expiring in 90 days. Current contractor performance satisfactory. Market research for rebid complete. Extending contract one year while developing new specifications with updated materials requirements."},
        {"id": 138, "title": "Terminal C cell phone lot expansion", "status": "open", "priority": "low", "days_ago": 19, "description": "Cell phone waiting lot near Terminal C at capacity during peak arrival periods. Expansion study underway. Land available for additional 50 spaces. Design and environmental review required. Budget request prepared."},
        {"id": 139, "title": "Operations manual update - security procedures", "status": "in_progress", "priority": "medium", "days_ago": 26, "description": "DFW Operations Manual security sections require update to reflect TSA regulation changes. Draft revisions complete. Stakeholder review in progress. Training program being developed for updated procedures."},
        {"id": 140, "title": "Terminal D energy efficiency audit", "status": "in_progress", "priority": "low", "days_ago": 17, "description": "Energy efficiency audit for Terminal D complete. Report identifies $340K annual savings opportunities. Quick wins implementation starting. Larger projects require capital investment. ROI analysis for budget process."},
        {"id": 141, "title": "Rental car facility shuttle stop improvements", "status": "open", "priority": "medium", "days_ago": 25, "description": "Rental car shuttle stops at terminals lacking adequate weather protection. Passenger complaints increasing. Design for covered waiting areas in development. Coordination with rental car companies on cost sharing."},
        {"id": 142, "title": "Terminal A escalator replacement project", "status": "open", "priority": "medium", "days_ago": 21, "description": "Escalators at Terminal A central atrium approaching 25-year service life. Manufacturer recommends replacement. Engineering assessment confirms recommendation. Capital project approved. Vendor selection in progress."},
        {"id": 143, "title": "Airfield vehicle maintenance facility upgrade", "status": "open", "priority": "low", "days_ago": 30, "description": "Airfield vehicle maintenance facility inadequate for current fleet size. Study recommending expansion of service bays and parts storage. Design funded. Construction budget request for FY2027 capital plan."},
        {"id": 144, "title": "Terminal E pre-conditioned air unit replacement", "status": "in_progress", "priority": "medium", "days_ago": 16, "description": "Pre-conditioned air units at Terminal E gates showing increased maintenance costs. Replacement of 8 units approved. First 4 units delivered. Installation progressing during overnight hours. Improved efficiency expected."},
        {"id": 145, "title": "Snow operations plan annual update", "status": "open", "priority": "medium", "days_ago": 22, "description": "Annual update of DFW Snow and Ice Control Plan required. Review committee formed. Equipment inventory verified. Chemical procurement contracts reviewed. Training schedule for winter season being developed."},
        {"id": 146, "title": "Terminal B power redundancy improvement", "status": "open", "priority": "high", "days_ago": 28, "description": "Power reliability study for Terminal B identified single points of failure. Engineering design for redundant feeds complete. Construction funding approved. Work scheduled to minimize operational impact. Critical for airline operations."},
        {"id": 147, "title": "Ground transportation app integration project", "status": "in_progress", "priority": "low", "days_ago": 18, "description": "Project to integrate ground transportation information into DFW mobile app. Real-time shuttle, taxi, and ride-share data. API development 70% complete. Beta testing with select users. Full launch targeted end of quarter."},
        {"id": 148, "title": "Terminal C holdroom seating refresh", "status": "open", "priority": "low", "days_ago": 24, "description": "Holdroom seating refresh program for Terminal C. Current seating 12 years old with visible wear. Replacement program phased over 18 months. First phase funded. Furniture selection meeting Design Criteria Manual standards."},
        {"id": 149, "title": "Airfield GPS vehicle tracking expansion", "status": "open", "priority": "medium", "days_ago": 20, "description": "Expansion of GPS tracking to contractor vehicles operating on airfield. Safety and compliance improvement. System capacity verified. Contractor coordination in progress. Implementation targeted before busy season."},
        {"id": 150, "title": "Terminal D customs area reconfiguration", "status": "in_progress", "priority": "medium", "days_ago": 27, "description": "CBP requesting customs area reconfiguration in Terminal D for improved passenger flow. Design alternatives developed with CBP input. Construction drawings 80% complete. Targeting construction during low-traffic period."},

        # ============================================================
        # BUCKET 4: 30+ days (50 tickets) - Long-term strategic projects
        # ============================================================
        {"id": 151, "title": "Terminal C modernization initiative - Phase 1 planning", "status": "open", "priority": "medium", "days_ago": 45, "description": "Terminal C originally opened in 1974, requires comprehensive modernization. Phase 1 planning includes updating passenger amenities, concessions redesign, improved wayfinding, and technology upgrades. Architect selection in progress. Estimated 5-year project timeline."},
        {"id": 152, "title": "Runway capacity expansion study - Environmental assessment", "status": "open", "priority": "medium", "days_ago": 35, "description": "DFW approaching runway capacity during peak operations. Studying feasibility of new crosswind runway or runway extensions. Environmental impact assessment initiated. FAA coordination required. Multi-year study expected."},
        {"id": 153, "title": "Sustainable airport operations initiative", "status": "in_progress", "priority": "low", "days_ago": 52, "description": "DFW commitment to carbon neutrality by 2030. Initiatives include LED lighting conversion, solar panel installation, electric GSE transition, and sustainable aviation fuel programs. Currently 40% complete on LED conversion. LEED certification target for new construction."},
        {"id": 154, "title": "New economy parking garage construction - Site planning", "status": "open", "priority": "low", "days_ago": 60, "description": "Parking demand projections indicate need for additional 3,500 economy parking spaces by 2027. Site selection and preliminary design underway. Must include EV charging infrastructure per sustainability standards. Estimated construction start Q3 2026."},
        {"id": 155, "title": "Ground support equipment electrification program", "status": "open", "priority": "low", "days_ago": 38, "description": "Transitioning airport-owned GSE fleet to electric vehicles. Requires electrical infrastructure upgrades at all terminals. Battery charging stations design in progress. Phased 7-year implementation plan."},
        {"id": 156, "title": "Airport-wide wayfinding and signage improvement project", "status": "in_progress", "priority": "low", "days_ago": 70, "description": "Comprehensive review of all airport signage for consistency, clarity, and ADA compliance. Passenger surveys indicate confusion at Terminal D/E connector and rental car center. Digital signage integration planned. 25% complete, focusing on Terminal A first."},
        {"id": 157, "title": "Terminal A satellite concourse feasibility study", "status": "open", "priority": "medium", "days_ago": 42, "description": "Long-term capacity planning study for Terminal A satellite concourse. Would add 12 gates connected via underground tunnel. Environmental and engineering feasibility assessments in progress. Horizon 2030 capital plan consideration."},
        {"id": 158, "title": "Central utility plant expansion project", "status": "in_progress", "priority": "medium", "days_ago": 55, "description": "Central utility plant expansion to support terminal growth. Adding chiller capacity and improving system redundancy. Construction 25% complete. New cooling tower installation in progress. Completion targeted end of year."},
        {"id": 159, "title": "Consolidated rental car facility study", "status": "open", "priority": "low", "days_ago": 48, "description": "Feasibility study for consolidated rental car facility to replace current distributed locations. Would improve customer experience and operational efficiency. Conceptual design complete. Financial analysis ongoing. Major capital investment required."},
        {"id": 160, "title": "Airport hotel development opportunity", "status": "open", "priority": "low", "days_ago": 65, "description": "Market study for on-airport hotel development. Identified demand for 300+ room full-service hotel. Site options evaluated. RFP for developer selection in preparation. Ground lease structure under review by legal."},
        {"id": 161, "title": "Airfield autonomous vehicle pilot program", "status": "in_progress", "priority": "low", "days_ago": 40, "description": "Pilot program testing autonomous airfield vehicles for baggage and cargo transport. Safety protocols developed with FAA coordination. Testing in controlled environment showing promising results. Expansion to limited airside operations planned."},
        {"id": 162, "title": "Terminal D international arrivals expansion", "status": "open", "priority": "medium", "days_ago": 58, "description": "International passenger arrivals facility in Terminal D at capacity. Expansion study recommending additional CBP processing capacity. Federal inspection services design criteria review with CBP. Congressional funding coordination required."},
        {"id": 163, "title": "Smart building technology integration", "status": "in_progress", "priority": "low", "days_ago": 72, "description": "Implementation of smart building technologies across all terminals. Includes IoT sensors for HVAC optimization, predictive maintenance, and energy management. Platform selection complete. Terminal B pilot in progress."},
        {"id": 164, "title": "Airside connector tunnel assessment", "status": "open", "priority": "medium", "days_ago": 33, "description": "Engineering assessment of airside connector tunnels between terminals. Evaluating structural condition, waterproofing, and life safety systems. Report identifies rehabilitation needs. Long-term capital plan item."},
        {"id": 165, "title": "Cargo facility expansion master plan", "status": "open", "priority": "medium", "days_ago": 50, "description": "Air cargo demand growth requires expanded facilities. Master plan development for south cargo complex expansion. Stakeholder input from cargo airlines collected. Environmental assessment initiated. Construction horizon 2028."},
        {"id": 166, "title": "Renewable energy installation project", "status": "in_progress", "priority": "medium", "days_ago": 62, "description": "Solar panel installation on parking garage rooftops and ground-mount array on airport property. Phase 1 (2MW) complete. Phase 2 (5MW) construction in progress. Power purchase agreement finalized. On track for 2030 carbon goals."},
        {"id": 167, "title": "Terminal B complete renovation program", "status": "open", "priority": "medium", "days_ago": 44, "description": "Comprehensive renovation program for Terminal B. Includes holdroom modernization, concession expansion, restroom upgrades, and infrastructure improvements. Program management consultant selected. 10-year implementation plan in development."},
        {"id": 168, "title": "Airport access road capacity improvements", "status": "open", "priority": "medium", "days_ago": 56, "description": "Traffic study identifying congestion points on airport access roads. International Parkway interchange improvements recommended. Coordination with TxDOT on project development. Federal funding opportunities being explored."},
        {"id": 169, "title": "Advanced passenger processing technology study", "status": "open", "priority": "low", "days_ago": 38, "description": "Evaluation of biometric passenger processing technologies. Facial recognition for boarding, customs clearance, and lounge access. Privacy framework development with legal. Pilot program scope in development with airline partners."},
        {"id": 170, "title": "Landside transit connection planning", "status": "open", "priority": "medium", "days_ago": 68, "description": "Planning for improved transit connections to DFW. Coordination with DART on Orange Line improvements and potential new station. Regional transit authority discussions ongoing. Long-term multimodal access vision development."},
        {"id": 171, "title": "Terminal E premium lounge cluster", "status": "open", "priority": "low", "days_ago": 42, "description": "Development opportunity for premium lounge cluster in Terminal E. Multiple airline partners expressing interest. Space planning for shared lounge concept. Design criteria and lease terms in negotiation."},
        {"id": 172, "title": "Airfield pavement management system upgrade", "status": "in_progress", "priority": "medium", "days_ago": 53, "description": "Upgrading airfield pavement management system to latest version. Includes mobile data collection, automated condition assessment, and capital planning integration. Data migration in progress. Training scheduled for maintenance staff."},
        {"id": 173, "title": "Emergency operations center relocation study", "status": "open", "priority": "medium", "days_ago": 36, "description": "Current emergency operations center space constraints limiting effectiveness. Study evaluating relocation options including new dedicated facility. Site options identified. Conceptual design and cost estimates in development."},
        {"id": 174, "title": "Terminal water reclamation system", "status": "open", "priority": "low", "days_ago": 75, "description": "Feasibility study for terminal water reclamation and reuse system. Would capture greywater for cooling tower makeup and irrigation. Engineering assessment complete. ROI favorable with utility rebates. Pilot project scoping."},
        {"id": 175, "title": "Concourse people mover system study", "status": "open", "priority": "medium", "days_ago": 47, "description": "Study of people mover options for long concourse walks in Terminals B and C. Evaluating moving walkways, horizontal escalators, and small vehicle systems. Passenger survey on preferences complete. Alternatives analysis in progress."},
        {"id": 176, "title": "Airport city development framework", "status": "open", "priority": "low", "days_ago": 80, "description": "Framework for airport city development on DFW property. Commercial, office, and hospitality uses. Market study complete. Development guidelines being drafted. Economic impact analysis shows significant job creation potential."},
        {"id": 177, "title": "Electric aircraft charging infrastructure planning", "status": "open", "priority": "low", "days_ago": 40, "description": "Planning for future electric aircraft charging infrastructure. Monitoring industry developments and airline announcements. Electrical capacity assessment for potential gate-based charging. Working with electric aircraft manufacturers."},
        {"id": 178, "title": "Terminal C pier extension project", "status": "open", "priority": "medium", "days_ago": 63, "description": "Terminal C pier extension to add 8 regional jet gates. Supports growth of connecting traffic. Environmental assessment complete. Design development 40% complete. Construction funding in capital plan."},
        {"id": 179, "title": "Airfield vehicle tracking system replacement", "status": "open", "priority": "medium", "days_ago": 34, "description": "Current airfield vehicle tracking system approaching obsolescence. Replacement project approved. System requirements gathered from stakeholders. RFP development in progress. Implementation timeline 18 months from contract award."},
        {"id": 180, "title": "Terminal D vertical circulation improvements", "status": "open", "priority": "medium", "days_ago": 58, "description": "Study of vertical circulation capacity in Terminal D. Escalator and elevator waits excessive during peak periods. Options include additional units and repositioning existing. ADA accessibility considerations paramount."},
        {"id": 181, "title": "Sustainable aviation fuel storage facility", "status": "in_progress", "priority": "medium", "days_ago": 48, "description": "Dedicated storage facility for sustainable aviation fuel at DFW fuel farm. Tank procurement complete. Site preparation underway. Piping design finalized. Supports airline sustainability commitments and DFW carbon goals."},
        {"id": 182, "title": "Airport microgrid development", "status": "open", "priority": "medium", "days_ago": 66, "description": "Development of airport microgrid for enhanced power reliability and renewable integration. Feasibility study complete. Battery storage sizing analysis in progress. Utility coordination ongoing. Supports resiliency goals."},
        {"id": 183, "title": "Employee facilities master plan", "status": "open", "priority": "low", "days_ago": 45, "description": "Master plan for employee facilities including break rooms, fitness center, and childcare. Employee survey identified priorities. Space assessment complete. Phased implementation plan in development. First phase targeting underserved areas."},
        {"id": 184, "title": "Terminal A federal inspection services upgrade", "status": "open", "priority": "medium", "days_ago": 55, "description": "Terminal A FIS facility upgrade to handle larger international aircraft. CBP processing capacity expansion. Baggage recheck configuration improvements. Design criteria coordination with CBP in progress."},
        {"id": 185, "title": "Real-time airport operations platform", "status": "in_progress", "priority": "medium", "days_ago": 38, "description": "Implementation of integrated real-time airport operations platform. Combines flight data, resource management, and performance metrics. Platform configuration 50% complete. Integration with existing systems ongoing."},
        {"id": 186, "title": "Noise mitigation program expansion", "status": "open", "priority": "low", "days_ago": 78, "description": "Expansion of residential noise mitigation program for affected communities. FAA funding application submitted. Program eligibility assessment in progress. Community outreach plan developed. Implementation dependent on federal funding."},
        {"id": 187, "title": "Terminal restroom sensor upgrade project", "status": "open", "priority": "low", "days_ago": 43, "description": "Upgrade of restroom fixture sensors across all terminals. Touch-free operation improvement. Water conservation features. Project scoped for phased implementation. First phase targeting high-traffic locations."},
        {"id": 188, "title": "Airfield lighting control system modernization", "status": "open", "priority": "high", "days_ago": 51, "description": "Airfield lighting control system modernization project. Current system approaching end of support. New system includes remote monitoring and automated testing. Design complete. Procurement specification in FAA review."},
        {"id": 189, "title": "Multi-modal transportation hub study", "status": "open", "priority": "medium", "days_ago": 70, "description": "Conceptual study for multi-modal transportation hub at DFW. Integrates rail, bus, rental car, and ride-share. Initial concepts developed. Stakeholder input being gathered. Long-term infrastructure vision component."},
        {"id": 190, "title": "Terminal E gate expansion project", "status": "in_progress", "priority": "medium", "days_ago": 33, "description": "Terminal E gate expansion adding 6 new international-capable gates. Design development 75% complete. Environmental permits obtained. Construction contractor selection in progress. Groundbreaking targeted Q2."},
        {"id": 191, "title": "Airport community partnership program", "status": "open", "priority": "low", "days_ago": 85, "description": "Development of enhanced community partnership program. Educational initiatives, workforce development, and local business opportunities. Program framework in development. Community advisory board formation in progress."},
        {"id": 192, "title": "Central deicing facility study", "status": "open", "priority": "medium", "days_ago": 46, "description": "Feasibility study for centralized deicing facility. Would improve efficiency and environmental compliance. Site options evaluated. Cost-benefit analysis favorable. Stakeholder airline feedback positive."},
        {"id": 193, "title": "Digital twin platform implementation", "status": "in_progress", "priority": "low", "days_ago": 62, "description": "Implementation of digital twin platform for facilities management. 3D models of all terminals and infrastructure. Data integration for real-time monitoring. Platform deployment 30% complete. Training program developed."},
        {"id": 194, "title": "Concession technology modernization program", "status": "open", "priority": "low", "days_ago": 39, "description": "Program to modernize concession technology across all terminals. Mobile ordering, digital menus, and payment integration. Requirements gathered from concessionaires. Platform evaluation in progress."},
        {"id": 195, "title": "Airfield infrastructure resilience assessment", "status": "open", "priority": "medium", "days_ago": 72, "description": "Comprehensive resilience assessment of critical airfield infrastructure. Climate change impact analysis. Flood risk evaluation. Extreme weather preparedness review. Recommendations being developed for capital planning."},
        {"id": 196, "title": "Terminal common-use technology refresh", "status": "open", "priority": "medium", "days_ago": 48, "description": "Technology refresh for common-use terminal equipment. Check-in kiosks, gate readers, and bag drop systems. Current equipment approaching end of life. Technology assessment complete. Procurement planning initiated."},
        {"id": 197, "title": "Employee transportation demand management", "status": "open", "priority": "low", "days_ago": 55, "description": "Program development for employee transportation demand management. Carpooling incentives, transit subsidies, and remote work policies. Baseline survey complete. Program options under evaluation with HR."},
        {"id": 198, "title": "Terminal B international capability assessment", "status": "open", "priority": "medium", "days_ago": 36, "description": "Assessment of Terminal B for potential international operations capability. Would require FIS facility development. CBP consultation initiated. Space analysis identifies viable configuration. Demand analysis in progress."},
        {"id": 199, "title": "Airport-wide LED conversion completion", "status": "in_progress", "priority": "medium", "days_ago": 65, "description": "Final phase of airport-wide LED lighting conversion. Targeting remaining areas in Terminals B and C. Project 80% overall complete. Energy savings exceeding projections. Completion targeted end of fiscal year."},
        {"id": 200, "title": "Long-term facility development plan update", "status": "open", "priority": "medium", "days_ago": 90, "description": "Comprehensive update of DFW Long-Term Facility Development Plan. 20-year horizon planning. Stakeholder input process complete. Demand forecasts updated. Draft plan in development. Board presentation scheduled Q4."},
    ]

    # Convert to full ticket dictionaries with datetime objects
    tickets = []
    for raw in raw_tickets:
        created_at = now - timedelta(days=raw["days_ago"])
        # Updated_at is usually more recent than created_at
        update_offset = min(raw["days_ago"], max(0, raw["days_ago"] - 2))
        updated_at = now - timedelta(days=update_offset)

        tickets.append({
            "id": raw["id"],
            "title": raw["title"],
            "status": raw["status"],
            "priority": raw["priority"],
            "created_at": created_at,
            "updated_at": updated_at,
            "description": raw["description"],
        })

    return tickets


# Generate tickets on module load
TICKETS = generate_tickets()


def get_all_tickets() -> List[Dict[str, Any]]:
    """Get all tickets with computed bucket field."""
    return [
        {**ticket, "bucket": calculate_bucket(ticket["created_at"])}
        for ticket in TICKETS
    ]


def get_ticket_by_id(ticket_id: int) -> Optional[Dict[str, Any]]:
    """Get a single ticket by ID."""
    for ticket in TICKETS:
        if ticket["id"] == ticket_id:
            return {**ticket, "bucket": calculate_bucket(ticket["created_at"])}
    return None
